version: '3.7'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --expire_logs_days=3 --secure-file-priv=""
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE, fix error mbind: Operation not permitted
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD:-mediawiki}
      - MYSQL_DATABASE=mediawiki
    volumes:
      - ./_initdb:/docker-entrypoint-initdb.d
      - mysql-data-volume:/var/lib/mysql

  web:
    image: ghcr.io/wikiworks/canasta:latest
    restart: unless-stopped
    depends_on:
      - db
      - elasticsearch
    links:
      - db
    environment:
      # Sourced from .env
      - MW_SITE_SERVER=${MW_SITE_SERVER:-http://localhost}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_POST_MAX_SIZE=${PHP_UPLOAD_MAX_FILESIZE:-10M}
      - PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-1000}
      - MW_SITEMAP_SUBDIR
      - MW_SITEMAP_IDENTIFIER
    volumes:
      - ./extensions:/var/www/mediawiki/w/extensions
      - ./skins:/var/www/mediawiki/w/skins
      - ./config:/mediawiki/config
      - ./images:/mediawiki/images
      - sitemap:/mediawiki/sitemap

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.20
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  caddy:
    image: caddy:2.4.6-alpine
    restart: unless-stopped
    entrypoint: caddy reverse-proxy --from ${MW_SITE_FQDN:-localhost} --to varnish:80
    ports:
      - "${PORT:-80}:80"
      - "443:443"
    volumes:
      - caddy-data:/data

  varnish:
    image: varnish:7.0.2-alpine
    restart: unless-stopped
    volumes:
      - ./_sources/configs/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /var/lib/varnish:exec

volumes:
  mysql-data-volume:
  elasticsearch:
  caddy-data:
  sitemap:
