apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  ports:
    - name: "80"
      port: 8081
      targetPort: 80
  selector:
    io.kompose.service: web
status:
  loadBalancer: { }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: MW_SITE_SERVER
              value: http://localhost
            - name: PHP_POST_MAX_SIZE
              value: 10M
            - name: PHP_UPLOAD_MAX_FILESIZE
              value: 10M
          image: ghcr.io/wikiteq/canasta:latest
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 80
          resources: { }
          volumeMounts:
            - mountPath: "/var/www/mediawiki/w/extensions"
              name: extensions
            - mountPath: "/var/www/mediawiki/w/skins"
              name: skins
            - mountPath: "/mediawiki/config"
              name: config
            - mountPath: "/mediawiki/images"
              name: images
            - mountPath: "/mediawiki/sitemap"
              name: sitemap
      restartPolicy: Always
      volumes:
        - name: extensions
          hostPath:
            path: "/opt/mediawiki/extensions"
            type: DirectoryOrCreate
        - name: skins
          hostPath:
            path: "/opt/mediawiki/skins"
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: "/opt/mediawiki/config"
            type: DirectoryOrCreate
        - name: images
          hostPath:
            path: "/opt/mediawiki/images"
            type: DirectoryOrCreate
        - name: sitemap
          hostPath:
            path: "/opt/mediawiki/sitemap"
            type: DirectoryOrCreate
status: { }
